services:
  - type: web
    name: website-scraper
    env: node
    plan: free
    buildCommand: npm install && node scripts/install-browsers.js
    startCommand: npm start
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
      - key: PORT
        value: 5000
